name: Solidity Contract Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    name: Hardhat Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test

  lint:
    name: Solidity Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check if .solhint.json exists
        run: ls -la && echo "Current directory content" && ls -la .solhint.json || echo ".solhint.json file not found"

      - name: Create .solhint.json if it doesn't exist
        run: |
          if [ ! -f .solhint.json ]; then
            echo '{ "extends": "solhint:recommended", "plugins": [], "rules": { "compiler-version": ["error", "^0.8.0"], "func-visibility": ["warn", { "ignoreConstructors": true }] } }' > .solhint.json
            echo "Created .solhint.json file"
          fi

      - name: Run Solhint
        run: npx solhint 'contracts/**/*.sol'